### ISSUE TITLE
As a user, upon entering the game, I (each player) receive 10 white cards, so I can play with them.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#1]
### Definition of done:
- [ ] Player should receive 10 random cards and these 10 cards are only visible to him/her.

### Task list:
- [x] #67
- [x] sopra-fs22-group-01/server#56
- [x] sopra-fs22-group-01/server#57
- [x] sopra-fs22-group-01/client#23
