### ISSUE TITLE
As a user, I want to supervote a card and express laughter if I find a card very funny.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#11]
### Definition of Done
- [x] Upon clicking, the supervote button laughter will be played through the speakers of all players
- [x] Every player has limited number of supervotes throughout the whole game.
- [x] A supervote counts as two votes.

### Task List:
- [x] sopra-fs22-group-01/client#7
- [x] sopra-fs22-group-01/server#35
- [x] sopra-fs22-group-01/server#36
