### ISSUE TITLE
fix joining a lobby as another user through the profile page

### ISSUE THREAD

**Issue by thphan21** [sopra-fs22-group-01/server#112]
### Task list:
- [ ] seperate profile page from the lobby page
- [ ] remove the "loop" that allows the same user to join a lobby multiple times
- [ ] the user can only join a lobby as themselves
