### ISSUE TITLE
As a user, I want to see the surname and points of all players to have an overview of the game progress.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#14]
### Definitions of Done
- [x] Every player sees the usernames of all players in the top left corner of the screen.
- [x] Every player sees the points of all players in the top left corner of the screen.

### Task List:
- [x] sopra-fs22-group-01/client#11
- [x] sopra-fs22-group-01/client#13
