### ISSUE TITLE
As a user, there is a possibility to write my own solution cards as well as sentence cards in order to have more variety.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#15]
### Definition of Done
- [x] The player can create a white card in the game lobby, (black card optional)
- [x] The player can choose if they want to play with or without the custom cards.
- [x] save custom text in user account in server

### Task List:
- [x] sopra-fs22-group-01/client#14
- [x] sopra-fs22-group-01/client#16

**Comment by SeyyidPalta** [comment]
This user story seems to be completed.
