### ISSUE TITLE
As a user, I want to create an account by providing a username and a password, so I can play the game.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#16]
### Definition of done:
- [x] The username must be unique.
- [x] Upon a successful registration, the player gets automatically logged in.
- [x] The account gets created in the database containing username and password.

### Tasks:
- [x] sopra-fs22-group-01/server#23
- [x] sopra-fs22-group-01/client#2
