### ISSUE TITLE
As a user, I want to login to my account by providing my username and password in order to join the game.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#17]
### Definition of Done:
- [x] If the username or password is wrong, an error message must be displayed.
- [x] When logged in, the player gets to their profile page.

### Task List:
- [x] sopra-fs22-group-01/server#28
- [x] sopra-fs22-group-01/client#29
