### ISSUE TITLE
As a user, when I get into the game lobby, I want to be presented with a pop-up window presenting the game rules and functionalities in order to know how the game works.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#19]
### Definition of Done 
- [x] Pop-up window displaying the game rules appears.
- [x] The window can be closed by the player if they are done reading or already know the rules.

### Task List:
- [x] sopra-fs22-group-01/server#29
- [x] sopra-fs22-group-01/client#3
