### ISSUE TITLE
As a user, I want to see a black card with an incomplete sentence, so I can play a white card that fits.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#2]
### Definition of Done
- [x] The same black card is presented to all players.
- [x] The gaps in the sentence must be clearly indicated.

### Task List:
- [x] sopra-fs22-group-01/client#26
- [x] sopra-fs22-group-01/client#27
