### ISSUE TITLE
As a user, I can change my username in the profile page to have more freedom.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#21]
### Definition of Done
- [ ] The player can change their username upon clicking a button.

### Task List:
- [x] sopra-fs22-group-01/client#20
- [x] sopra-fs22-group-01/client#41
- [x] sopra-fs22-group-01/client#42
- [x] sopra-fs22-group-01/server#84
- [x] #85
