### ISSUE TITLE
As a user, I can choose a card out of the 10 to play.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#3]
### Definition of Done:
- [x] Upon clicking a card, it'll become the card the player wants to play.
- [x] The player can see which card they have chosen by having the selected card being framed.

### Task List:
- [x] sopra-fs22-group-01/client#8
- [x] sopra-fs22-group-01/client#9
- [x] sopra-fs22-group-01/server#78
