### ISSUE TITLE
As a user, I have limited time to choose a card while a timer counts down.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#4]
### Definition of Done
- [x] The player should see a countdown to see how much time is left.
- [ ] If time's up and no card was chosen, a random one will be played.

### Task List
- [x] sopra-fs22-group-01/client#12
- [x] sopra-fs22-group-01/server#45
