### ISSUE TITLE
As a user, when time's up, I will be redirected to a screen where I should be presented with all the cards chosen by other players, with the black card on top, to see what cards the other players have chosen.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#6]
### Definition of done
- [ ] The player can see all solution cards at once (revealed).

### Task List:
- [x] sopra-fs22-group-01/server#51
- [x] sopra-fs22-group-01/client#19
