### ISSUE TITLE
As a User at the end of the game, I want to see the winner so I know who won the game.

### ISSUE THREAD

**Issue by lsenni** [sopra-fs22-group-01/server#68]
### Definition of done:
- [ ]Player can see which player has won at the end of the game.

### Task list:
- [ ]Write the logic which finds out who is the winner of the game.
- [ ]Write the frontend logic which displays the winner at the end of the game
