### ISSUE TITLE
As a User at the end of the game, I want to see the winner so I know who won the game.

### ISSUE THREAD

**Issue by lsenni** [sopra-fs22-group-01/server#69]
### Definition of done:
- [x] Player can see which player has won at the end of the game.

### Task list:
- [x] sopra-fs22-group-01/server#70
- [x] sopra-fs22-group-01/client#30
- [x] #73
- [x] #91
