### ISSUE TITLE
As a user, I want to hear that the API reads all cards out loud with a funny voice.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#7]
### Definition of Done:
- [ ] The player should hear a voice reading out the card.
- [ ] All cards should be well legible to the user.
- [ ] The voice of the API will be changed in each round. (optional)

### Task List
- [x] sopra-fs22-group-01/client#21
- [x] sopra-fs22-group-01/client#22
