### ISSUE TITLE
Use JSON file for cards and create correct usage for it in backend.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#74]
### Task List:
- [ ] Read JSON File
- [ ] Create card instances for black and white
- [ ] save cards in the backend
