### ISSUE TITLE
As a user, during the countdown I should make a choice and elect a favorite solution card.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#8]
### Definition of Done
- [ ] The player can vote for a card (except for their own card).
- [ ] Thumbs up/like emojis are lined up along the voted cards, for everyone visible (likes visible, anonymously voted)

### Task List:
- [x] sopra-fs22-group-01/server#58
- [x] sopra-fs22-group-01/client#24
