### ISSUE TITLE
As a user, I want to see the winning card after the election to know who won the round.

### ISSUE THREAD

**Issue by SeyyidPalta** [sopra-fs22-group-01/server#9]
### Definition of Done
- [ ] The most voted card together with the black one will get bigger, and the other cards falling in the background.
- [ ] The name of the player, who got the most of the votes, gets displayed.
- [ ] The winner of the round will receive a message that they won a point.

### Task List:
- [x] https://github.com/sopra-fs22-group-01/server/issues/62
- [x] https://github.com/sopra-fs22-group-01/client/issues/25
